version: '3.9'

services:
  elasticsearch:
    image: elasticsearch:7.17.21
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'
    networks:
      - elk-network

  logstash:
    image: logstash:7.17.21
    container_name: log
    environment:
      discovery.seed_hosts: logstash
    ports:
      - '5000:5000/tcp'
      - '5000:5000/udp'
      - '5044:5044'
      - '9600:9600'
    depends_on:
      - elasticsearch
    networks:
      - elk-network
    command: logstash -f /usr/share/logstash/pipeline/logstash-nginx.config

  kibana:
    image: kibana:7.17.21
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
    networks:
      - elk-network

networks:
  elk-network:
    driver: bridge
