version: '3.9'

services:
  db:
    image: postgres:alpine3.20
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'suitNBA'
    ports:
      - '5433:5432'
    networks:
      - elk-network

networks:
  elk-network:
    driver: bridge
