package org.forsstudio.nbatestsuit.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PlayerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlayerAllPropertiesEquals(Player expected, Player actual) {
        assertPlayerAutoGeneratedPropertiesEquals(expected, actual);
        assertPlayerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlayerAllUpdatablePropertiesEquals(Player expected, Player actual) {
        assertPlayerUpdatableFieldsEquals(expected, actual);
        assertPlayerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlayerAutoGeneratedPropertiesEquals(Player expected, Player actual) {
        assertThat(expected)
            .as("Verify Player auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlayerUpdatableFieldsEquals(Player expected, Player actual) {
        assertThat(expected)
            .as("Verify Player relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlayerUpdatableRelationshipsEquals(Player expected, Player actual) {}
}
